### ISSUE TITLE
add a general survey and specialised surveys for each of the game

### ISSUE THREAD

**Issue by cmwaters** [teloscope/teloscope#4]
...

**Comment by viktornd** [comment]
Suggested changes to the final questions:

What do you think of games as a tool for assessing someone's competency for a role. What do you think are the strengths and weaknesses?
What do you think of games as a tool **used by companies to assess candidates competencies**. What do you think are the strengths and weaknesses?

What would you like to see more of generally when it comes to recruitment? What would you like to see less of?
What recruitment processes have you heard of or experienced which you liked? What would you like to see less of?

What do you think of the prospect of multiplayer games? Do you think it may be valuable to peer team members and candidates together to see how a candidate might work in the existing team?
What do you think of the prospect of multiplayer games? Do you think it may be valuable method of showing how you work with others in a team environment?


Do you have a game or idea in mind that you think might be interesting to use in this context? (no suggested changes from me)


Any final remarks?


I was also thinking to add a question around remote working positions but I am still thinking about how to do this best

**Comment by cmwaters** [comment]
Okay, these questions seem apt. I will make the changes to the questions on my branch. It would be nice to get the minimum working version of this site up by the end of this weekend and then we can build on stuff from there.

**Comment by cmwaters** [comment]
Solved here: #5 but we should endeavour to improve the questions and make them more specific for each of the games
